import type { HumanitarianMapPoint, HumanitarianRegion } from './model';

export const DEMO_REGIONS: readonly HumanitarianRegion[] = [
  {
    id: 'co-ris-pereira',
    name: 'Pereira',
    department: 'Risaralda',
    center: [-75.6946, 4.8133],
    zoom: 12.3,
  },
  {
    id: 'co-ris-dosquebradas',
    name: 'Dosquebradas',
    department: 'Risaralda',
    center: [-75.676, 4.835],
    zoom: 12.5,
  },
  {
    id: 'co-qui-armenia',
    name: 'Armenia',
    department: 'Quindío',
    center: [-75.6811, 4.5339],
    zoom: 12.2,
  },
];

export const DEMO_POINTS: readonly HumanitarianMapPoint[] = [
  {
    id: 'demo-need-centro',
    regionId: 'co-ris-pereira',
    category: 'need',
    title: 'Colchonetas y cobijas',
    neighborhood: 'Centro',
    description: 'Solicitud demostrativa para familias evacuadas.',
    severity: 'critical',
    verificationStatus: 'verified',
    observedAt: '2026-08-13T05:40:00-05:00',
    coordinates: [-75.6946, 4.8143],
  },
  {
    id: 'demo-aid-san-nicolas',
    regionId: 'co-ris-pereira',
    category: 'aid-center',
    title: 'CAFE San Nicolás',
    neighborhood: 'San Nicolás',
    description: 'Centro de acopio publicado; confirmar horario y capacidad antes de desplazarse.',
    address: 'Sector San Nicolás, Pereira',
    schedule: 'Horario demostrativo: confirmar antes de salir',
    acceptedItems: ['Higiene', 'Cobijas', 'Alimentos no perecederos'],
    sourceLabel: 'Ficha demostrativa',
    severity: 'low',
    verificationStatus: 'official',
    observedAt: '2026-08-13T05:10:00-05:00',
    coordinates: [-75.7048, 4.8068],
  },
  {
    id: 'demo-damage-rio',
    regionId: 'co-ris-pereira',
    category: 'damage',
    title: 'Evaluación estructural pendiente',
    neighborhood: 'Río Otún',
    description: 'Punto demostrativo; no representa un diagnóstico oficial.',
    severity: 'high',
    verificationStatus: 'reported',
    observedAt: '2026-08-13T04:55:00-05:00',
    coordinates: [-75.6975, 4.8212],
  },
  {
    id: 'demo-aid-remanso',
    regionId: 'co-ris-pereira',
    category: 'aid-center',
    title: 'CAFE El Remanso',
    neighborhood: 'El Remanso',
    description: 'Centro de acopio publicado junto al centro de salud.',
    address: 'Junto al centro de salud El Remanso',
    schedule: 'Horario demostrativo: confirmar antes de salir',
    acceptedItems: ['Agua', 'Higiene', 'Protección personal'],
    sourceLabel: 'Ficha demostrativa',
    severity: 'low',
    verificationStatus: 'official',
    observedAt: '2026-08-13T05:10:00-05:00',
    coordinates: [-75.6676, 4.7979],
  },
];
